name: 'pinterest_source'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
vars:
  ad_group_history: "{{ source('pinterest_ads','ad_group_history') }}"
  campaign_history: "{{ source('pinterest_ads','campaign_history') }}"
  pin_promotion_history: "{{ source('pinterest_ads','pin_promotion_history') }}"
  pin_promotion_report: "{{ source('pinterest_ads','pin_promotion_report') }}"
  advertiser_history: "{{ source('pinterest_ads','advertiser_history') }}"
  pin_promotion_report_pass_through_metric: []
models:
  pinterest_source:
    +schema: stg_pinterest
    +materialized: table
    tmp:
      +materialized: view
