name: 'pinterest_source'
version: '0.10.2'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  ad_group_history: "{{ source('pinterest_ads','ad_group_history') }}"
  campaign_history: "{{ source('pinterest_ads','campaign_history') }}"
  pin_promotion_history: "{{ source('pinterest_ads','pin_promotion_history') }}"
  pin_promotion_report: "{{ source('pinterest_ads','pin_promotion_report') }}"
  ad_group_report: "{{ source('pinterest_ads','ad_group_report') }}"
  advertiser_history: "{{ source('pinterest_ads','advertiser_history') }}"
  advertiser_report: "{{ source('pinterest_ads','advertiser_report') }}"
  campaign_report: "{{ source('pinterest_ads','campaign_report') }}"
  keyword_history: "{{ source('pinterest_ads','keyword_history') }}"
  keyword_report: "{{ source('pinterest_ads','keyword_report') }}"
  pinterest__pin_promotion_report_passthrough_metrics: []
  pinterest__ad_group_report_passthrough_metrics: []
  pinterest__advertiser_report_passthrough_metrics: []
  pinterest__campaign_report_passthrough_metrics: []
  pinterest__keyword_report_passthrough_metrics: []
models:
  pinterest_source:
    +schema: pinterest_source
    +materialized: table
    tmp:
      +materialized: view
